"""
Documentation builder for spatial visual previews (DOCS-01).

Provides a reproducible CLI entry that emits pre-rendered Leaflet/Folium HTML,
SVG, and PNG preview bundles for every GEO-INFER domain module, plus a preview
index page referenced from the module documentation.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from geo_infer_intra.core.documentation.visual_preview import (
    MODULE_PROFILES,
    generate_module_preview_suite,
)

# Anchor used when a module page references its interactive spatial preview.
_PREVIEW_SECTION_TITLE = "## 🗺️ Interactive Spatial Preview"


def _render_preview_markdown(module_id: str, slug: str) -> str:
    """Render a Markdown snippet that anchors a module to its preview bundle."""
    friendly_name = MODULE_PROFILES[module_id]["name"]
    return "\n".join(
        [
            _PREVIEW_SECTION_TITLE,
            "",
            f"Pre-rendered spatial snapshot for **GEO-INFER-{module_id}** "
            f"(*{friendly_name}*). Reproducible preview cards are generated by "
            "`geo_infer_intra.core.documentation.visual_preview`.",
            "",
            "| Preview | Widget |",
            "| --- | --- |",
            f"| ![GEO-INFER-{module_id} Leaflet Preview](previews/{slug}_preview.svg) | "
            "Leaflet HTMLMap · SVG vector · PNG raster |",
            "",
            "> **Reproducible contract:** each map ships as "
            f"`{slug}_preview.html`, `{slug}_preview.svg`, `{slug}_preview.png`, "
            f"and `{slug}_preview.manifest.json` beneath `previews/`. The receipt "
            "records an input SHA-256 and artifact accessibility checks.",
            "",
        ]
    )


def _inject_preview_section(module_doc: Path, module_id: str) -> bool:
    """Insert (or refresh) the interactive spatial preview section into a page."""
    slug = f"geo-infer-{module_id.lower()}"
    text = module_doc.read_text(encoding="utf-8")
    section = _render_preview_markdown(module_id, slug)

    if _PREVIEW_SECTION_TITLE in text:
        # Replace the existing preview section (from title to next heading).
        lines = text.splitlines()
        start = next(
            i for i, line in enumerate(lines) if line.strip() == _PREVIEW_SECTION_TITLE
        )
        end = len(lines)
        for j in range(start + 1, len(lines)):
            if lines[j].startswith("## ") and lines[j].strip() != _PREVIEW_SECTION_TITLE:
                end = j
                break
        new_lines = lines[:start] + section.splitlines() + lines[end:]
        module_doc.write_text("\n".join(new_lines), encoding="utf-8")
        return True

    module_doc.write_text(text.rstrip() + "\n\n" + section, encoding="utf-8")
    return True


def build_previews(modules_dir: Path, output_dir: Path) -> int:
    """Generate preview bundles for all 44 modules and write a preview index."""
    output_dir.mkdir(parents=True, exist_ok=True)

    emitted = 0
    index_lines = [
        "# Spatial Preview Cards",
        "",
        "Auto-generated single and static preview snapshots for all GEO-INFER "
        "domain modules, produced by "
        "`geo_infer_intra.core.documentation.visual_preview`.",
        "",
        "| Module | Preview |",
        "| --- | --- |",
    ]

    for module_id in sorted(MODULE_PROFILES.keys()):
        slug = f"geo-infer-{module_id.lower()}"
        generate_module_preview_suite(module_id, output_dir)
        emitted += 1

        module_doc = modules_dir / f"geo-infer-{module_id.lower()}.md"
        if module_doc.is_file():
            _inject_preview_section(module_doc, module_id)

        index_lines.append(
            f"| [{module_id}](geo-infer-{module_id.lower()}.md) | "
            f"open `previews/{slug}_preview.svg` |"
        )

    index_lines.append("")
    (modules_dir / "previews_index.md").write_text(
        "\n".join(index_lines), encoding="utf-8"
    )
    return emitted


def main() -> int:
    """CLI entry point for regenerating module spatial preview documentation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--modules-dir",
        type=Path,
        default=Path("GEO-INFER-INTRA/docs/modules"),
        help="Path to the documentation modules directory.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("GEO-INFER-INTRA/docs/modules/previews"),
        help="Directory into which preview bundle files are written.",
    )
    args = parser.parse_args()

    if not args.modules_dir.is_dir():
        raise SystemExit(f"Modules docs directory missing: {args.modules_dir}")

    emitted = build_previews(args.modules_dir, args.output_dir)
    print(f"Emitted {emitted} spatial preview bundles to {args.output_dir}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())