#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup, find_packages

setup(
    name="geo-infer-test",
    version="0.1.0",
    description="Comprehensive testing framework for the GEO-INFER ecosystem",
    author="GEO-INFER Team",
    author_email="info@geo-infer.org",
    url="https://github.com/activeinference/GEO-INFER/tree/main/GEO-INFER-TEST",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    include_package_data=True,
    install_requires=[
        "pytest>=7.0.0",
        "pytest-cov>=4.0.0",
        "pytest-xdist>=3.0.0",
        "pytest-mock>=3.10.0",
        "pytest-html>=3.1.0",
        "pytest-benchmark>=4.0.0",
        "pytest-timeout>=2.1.0",
        "coverage[toml]>=7.0.0",
        "numpy>=1.20.0",
        "pandas>=1.3.0",
        "geopandas>=0.10.0",
        "requests>=2.28.0",
        "pyyaml>=6.0",
        "jsonschema>=4.0.0",
        "hypothesis>=6.0.0",
        "faker>=18.0.0",
        "factory-boy>=3.2.0",
        "selenium>=4.0.0",
        "locust>=2.0.0",
        "memory-profiler>=0.60.0",
        "psutil>=5.9.0",
        "tabulate>=0.9.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "jinja2>=3.1.0",
    ],
    extras_require={
        "dev": [
            "black>=23.3.0",
            "flake8>=6.0.0",
            "isort>=5.12.0",
            "mypy>=1.0.0",
            "pre-commit>=3.0.0",
        ],
        "docs": [
            "sphinx>=5.0.0",
            "sphinx-rtd-theme>=1.2.0",
            "myst-parser>=1.0.0",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Testing",
        "Topic :: Scientific/Engineering :: GIS",
        "Topic :: Software Development :: Quality Assurance",
    ],
    keywords="testing, geospatial, geo-infer, quality assurance, test automation",
    python_requires=">=3.9",
    entry_points={
        "console_scripts": [
            "geo-test=geo_infer_test.cli:main",
            "geo-test-runner=geo_infer_test.runners.main:main",
            "geo-test-report=geo_infer_test.reporting.generator:main",
        ],
    },
) 